### ISSUE TITLE
Create Action that updates documentation

### ISSUE THREAD

**Issue by oaustegard** [oaustegard/bookmarklets#5]
Craft an Action that will consider a commit and update the repo README with descriptions of each bookmarklet.

**Comment by oaustegard** [comment]
```

name: Generate File Summaries

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.github/**'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.github/**'
      - 'LICENSE'

jobs:
  generate-summaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @anthropic-ai/sdk fs-extra glob

      - name: Generate Summaries
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: node .github/scripts/generate-summaries.js
        
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet || git commit -m "docs: Update file summaries [skip ci]"
          git push

```
